{% set name = "cuda-gdb" %}
{% set version = "12.5.82" %}
{% set cuda_version = "12.5" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_gdb/{{ platform }}/cuda_gdb-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: 25bc68ff2ec6133ad7271aece6535f4820b057821421d16932a8c9080b162520  # [linux64]
  sha256: 0cecc82647b80b42c3e7cd934485407588d0143917ebd3673bfaf935855ef252  # [aarch64]

build:
  number: 0
  skip: true  # [osx or win or ppc64le]

test:
  commands:
    - test -f $PREFIX/bin/cuda-gdb
    - test -f $PREFIX/bin/cuda-gdbserver
    - test -f $PREFIX/extras/Debugger/Readme.txt
    - test -d $PREFIX/share/gdb/syscalls
    - test -d $PREFIX/share/gdb/system-gdbinit

outputs:
  - name: cuda-gdb
    files:
      - bin/cuda-gdb
      - bin/cuda-gdbserver
      - extras/Debugger
      - share/gdb
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ stdlib("c") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
      host:
        - cuda-version {{ cuda_version }}
        - expat                                 # [aarch64]
        - gmp
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    # Tests are defined at the top level, due to package/output name conflicts.
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: CUDA-GDB is the NVIDIA tool for debugging CUDA applications
      description: |
        CUDA-GDB is the NVIDIA tool for debugging CUDA applications running on Linux.
        CUDA-GDB is an extension to the x86-64 port of GDB, the GNU Project debugger.
      doc_url: https://docs.nvidia.com/cuda/cuda-gdb/index.html

  - name: cuda-gdb-src
    files:
      - extras/cuda-gdb-{{ version }}.src.tar.gz
    requirements:
      build:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      commands:
        - test -f $PREFIX/extras/cuda-gdb-{{ version }}.src.tar.gz
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: CUDA-GDB is the NVIDIA tool for debugging CUDA applications
      description: |
        CUDA-GDB is the NVIDIA tool for debugging CUDA applications running on Linux.
        CUDA-GDB is an extension to the x86-64 port of GDB, the GNU Project debugger.
      doc_url: https://docs.nvidia.com/cuda/cuda-gdb/index.html

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: CUDA-GDB is the NVIDIA tool for debugging CUDA applications
  description: |
        CUDA-GDB is the NVIDIA tool for debugging CUDA applications running on Linux.
        CUDA-GDB is an extension to the x86-64 port of GDB, the GNU Project debugger.
  doc_url: https://docs.nvidia.com/cuda/cuda-gdb/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
